services:
  worker:
    image: starterkit-sequencer
    build:
      dockerfile: ./docker/base/Dockerfile
      context: ../..
    container_name: starterkit-worker
    environment:
      - PROTOKIT_LOG_LEVEL=${PROTOKIT_LOG_LEVEL:-INFO}
    profiles:
      - worker
    depends_on:
      - redis
    networks:
      - db-net
    command: ["${INDEX_JS}", "${PROTOKIT_ENV}", "${WORKER_CONFIG}" ]
